/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class kthandler_KnightTourHandler */

#ifndef _Included_kthandler_KnightTourHandler
#define _Included_kthandler_KnightTourHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kthandler_KnightTourHandler
 * Method:    KnightTour_JavaCaller
 * Signature: (IIII[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kthandler_KnightTourHandler_KnightTour_1JavaCaller
  (JNIEnv *, jobject, jint, jint, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
