/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    KnightTour
 * Signature: (IIII[I)Z
 */
JNIEXPORT jboolean JNICALL Java_Test_KnightTour
  (JNIEnv *, jobject, jint, jint, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
